-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Peli CASCADE;
DROP TABLE IF EXISTS Turnaustapahtuma CASCADE;
DROP TABLE IF EXISTS Turnaus CASCADE;
DROP TABLE IF EXISTS Ottelu CASCADE;